name: PUBLISH
on: 
  push:
     branches: [ master ]
  workflow_dispatch:
 

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.qlicks.nl/
          token: ${{ secrets.NPM_TOKEN_PUBLISH }}
